# Generated by Django 4.0.2 on 2022-03-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phonenumber', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='staff_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phonenumber', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('image', models.FileField(max_length=150, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=150)),
            ],
        ),
    ]
