# Generated by Django 4.1.1 on 2023-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metroconnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=150)),
                ('complainsubject', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=150)),
                ('offer', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='parkings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(max_length=150)),
                ('slot', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainname', models.CharField(max_length=150)),
                ('startstation', models.CharField(max_length=150)),
                ('endstation', models.CharField(max_length=150)),
                ('distance', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=150)),
                ('startstation', models.CharField(max_length=150)),
                ('endstation', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('distance', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
                ('trainno', models.CharField(max_length=150)),
                ('sid', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainno', models.CharField(max_length=150)),
                ('trainname', models.CharField(max_length=150)),
                ('traintime', models.CharField(max_length=150)),
                ('stationname', models.CharField(max_length=150)),
                ('trainimage', models.FileField(max_length=150, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='userpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=150)),
                ('startstation', models.CharField(max_length=150)),
                ('endstation', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
                ('trainno', models.CharField(max_length=150)),
                ('cardname', models.CharField(max_length=150)),
                ('cardnumber', models.CharField(max_length=150)),
                ('cardtype', models.CharField(max_length=150)),
                ('sid', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='userrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=150)),
                ('startstation', models.CharField(max_length=150)),
                ('endstation', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='userslotpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(max_length=150)),
                ('startstation', models.CharField(max_length=150)),
                ('endstation', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
                ('cardname', models.CharField(max_length=150)),
                ('cardnumber', models.CharField(max_length=150)),
                ('cardtype', models.CharField(max_length=150)),
            ],
        ),
    ]
